//local host for schools

### Get all schools
GET http://localhost:3000/schools/

### Get a single school
GET http://localhost:3000/schools/67a2a3ee4c0364cd98e2eb67

### Create school
POST http://localhost:3000/schools/ http/1.1
Content-Type: application/json

{
    "name": "Mandi University",
    "location": "Mytown, UT ",
    "established": 2025,
    "type": "Private",
    "student_population": 5,
    "website": "https://www.mandiuniversity.edu",
    "mascot": "Tiger"
}

### Put school
PUT http://localhost:3000/schools/67a2a3ee4c0364cd98e2eb67 http/1.1    
Content-Type: application/json

{
    "name": "University of Utah",
    "location": "Salt Lake City, UT",
    "established": 1850,
    "type": "Public",
    "student_population": 32000,
    "website": "https://www.utah.edu",
    "mascot": "Swoop the Falcon"
}

### Delete school
DELETE http://localhost:3000/schools/67a2bd0822952e4ac7876d8a http/1.1

//local host for roommates

### Get all roommates
GET http://localhost:3000/roommates/

### Get a single roommate
GET http://localhost:3000/roommates/67a2c1d54c0364cd98e2eb75

### Create roommate
POST http://localhost:3000/roommates/ http/1.1
Content-Type: application/json

{
   "name": "Mandi Beau",
    "age" :  "22",
    "major": "Computer Science",
    "contact": {
            "phone": "555-555-5555",
            "email": "mandi.beau@email.com"
        }
    }


### Put roommates
PUT http://localhost:3000/roommates/67a2c1d54c0364cd98e2eb75 http/1.1    
Content-Type: application/json

{
    name: "Alice Johnson",
    age :  "19",
    major: "Computer Science",
    contact: {
        phone: "555-555-1235",
        email: "alice.johnson@email.com"
    }
}

### Delete roommate
DELETE http://localhost:3000/roommates/67a2d61e0172680b648ca5ff http/1.1

//Render server
### Get all contacts
GET https://cse341-project2-4wgf.onrender.com/schools/

### Get a single contact
GET https://cse341-project2-4wgf.onrender.com/schools//67a2a3ee4c0364cd98e2eb67

### Create contact
POST https://cse341-project2-4wgf.onrender.com/schools/ http/1.1
Content-Type: application/json

{
   "name": "Mandi University",
    "location": "Mytown, UT ",
    "established": 2025,
    "type": "Private",
    "student_population": 5,
    "website": "https://www.mandiuniversity.edu",
    "mascot": "Tiger"
}

### Put contact
PUT https://cse341-project2-4wgf.onrender.com/schools/67a2a3ee4c0364cd98e2eb67 http/1.1    
Content-Type: application/json

{
    "name": "University of Utah",
    "location": "Salt Lake City, UT",
    "established": 1860,
    "type": "Public",
    "student_population": 32000,
    "website": "https://www.utah.edu",
    "mascot": "Swoop the Falcon"
}

### Delete contact
DELETE https://cse341-project2-4wgf.onrender.com/schools/67a2bd0822952e4ac7876d8a http/1.1